sudo: required
services:
  - docker

before_install:
  - docker build -t marius360/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run marius360/react-test npm test -- --coverage

after_success:
  - docker build -t marius360/multi-client ./client
  - docker build -t marius360/multi-nginx ./nginx
  - docker build -t marius360/multi-server ./server
  - docker build -t marius360/multi-worker ./worker
  # Log in to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push marius360/multi-client
  - docker push marius360/multi-nginx
  - docker push marius360/multi-server
  - docker push marius360/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-237319134422
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
